<?php

namespace InventoryBundle\Repository;

/**
 * StoreTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
