---
- name: Remove apache
  apt: name=apache2 state=absent force=yes
  become: True

- name: Installing nginx repository key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - http://nginx.org/keys/nginx_signing.key
  become: True

- name: Adding source repositories to sources.list.d
  copy: src=nginx.list dest=/etc/apt/sources.list.d/nginx.list
  become: True

- name: install nginx web server
  apt: pkg=nginx state=installed
  become: True

- name: Ensure sites-enabled dir
  file: path=/etc/nginx/sites-enabled state=directory owner={{ nginx_user }}
  become: True

- name: Ensure pool directory
  file: path=/etc/php/7.1/fpm/pool.d state=directory mode=0755 recurse=yes
  become: True

- name: apply nginx server and virtualhost config templates
  template: src={{ item.src }} dest={{ item.dest }}  mode=0644 owner=root group=root
  become: True
  with_items:
    - { src : 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src : 'status.conf.j2', dest: '/etc/nginx/sites-enabled/status.conf' }
    - { src : 'store.local.j2', dest: '/etc/nginx/sites-enabled/store.local.conf' }
    - { src : 'www.conf.j2', dest: '/etc/php/7.1/fpm/pool.d/www.conf' }
    - { src : 'php.ini.j2', dest: '/etc/php/7.1/fpm/php.ini' }

- name: nix default nginx config
  file: dest=/etc/nginx/sites-enabled/default state=absent
  become: True

- name: nix additional nginx configuration directory
  file: dest=/etc/nginx/conf.d/default.conf state=absent
  become: True

- name: chown html directory to be owned by www-data
  file: path=/usr/share/nginx/html owner=www-data group=www-data mode=0755
  become: True

- name: Remove nginx default web files
  file: path=/usr/share/nginx/html/{{item}} state=absent
  with_items:
    - index.html
    - 50x.html
  ignore_errors: yes
  become: True

- name: Make sure /var/www/.ssh exists
  file: path={{ item }} state=directory owner=www-data group=www-data mode=0755
  become: True
  with_items:
    - /var/www/.ssh

- name: restart nginx
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nginx
  become: True
